name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Restart Application
        run: |
          ssh ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} '
            set -ex
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            cd /var/www/pythonserver
            chmod 600 deploy_key
            GIT_SSH_COMMAND="ssh -i deploy_key -o IdentitiesOnly=yes" git pull origin main
            ./venv/bin/pip install -r requirements.txt
            sudo systemctl restart scriber
          '